spring:
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/hyunbindev/dongdaemunfriends-msa.git"
          search-path: "config/config-repo"
          username: hyunbinDev
          password: ${GIT_ACCESS_KEY}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://eurekaserver:8761/eureka/