server:
  port: 8888
  tomcat:
    relaxed-host-validation: true

spring:
  application:
    name: config

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  cloud:
    config:
      server:
        git:
          uri: https://github.com/hyunbindev/dongdaemunfriends-msa.git
          search-paths: config/config-repo
          username: hyunbinDev
          password: ${GIT_ACCESS_KEY}
          default-label: master

encrypt:
  key: ${ENCRYPT_KEY}
logging:
  level:
    org.springframework.cloud.config.server: DEBUG
    org.eclipse.jgit: DEBUG