services:
  eurekaserver:
    image: eurekaserver:latest
    ports:
      - "8761:8761"
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  api-gateway:
    image: hyunbindev/dongdaemunfriends-api-gateway:latest
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8000:8000"
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  
  config:
    image: hyunbindev/dongdaemunfriends-config:latest
    networks:
      - app-network
      - GIT_ACCESS_KEY=${GIT_ACCESS_KEY}
      - ENCRYPT_KEY=${ENCRYPT_KEY}
      - SPRING_PROFILES_ACTIVE=prod
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure


networks:
  app-network:
    driver: overlay
