services:
  eurekaserver:
    image: eurekaserver:latest
    ports:
      - "8761:8761"
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  api-gateway:
    image: hyunbindev/dongdaemunfriends-api-gateway:latest
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8000:8000"
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  config:
    image: hyunbindev/dongdaemunfriends-config:latest
    environment:
      - GIT_ACCESS_KEY=${GIT_ACCESS_KEY}
      - ENCRYPT_KEY=${ENCRYPT_KEY}
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  board:
    image: hyunbindev/dongdaemunfriends-board:latest
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  app-network:
    driver: overlay