server:
  port: 8000

eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

spring:
  config:
    import: "configsserver:http://dongdaemunkiller_config:8888"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ddm-friends-api
          uri: lb://dongdaemunkiller_was
          predicates:
            - Path=/api/**
