eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

spring:
  application:
    name: board
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  cloud:
    config:
      enabled: true
      import: optional:configserver:http://config:8888
      label: master
