name: Board-Service CI/CD Pipe Line

on:
  push:
    branches:
      - master
    paths:
      - "board/**"
  
jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Gradle Build
        working-directory: ./board
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test
      
      - name: Build Docker Image
        working-directory: ./board
        run: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/dongdaemunfriends-board
          VERSION=${{ github.sha }}
          docker build -t $IMAGE:$VERSION -t $IMAGE:latest .

      - name: Push Docker Image
        run: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/dongdaemunfriends-board
          VERSION=${{ github.sha }}
          docker push $IMAGE:$VERSION
          docker push $IMAGE:latest

      - name: Deploy to Swarm
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/dongdaemunfriends-board:latest
            docker service update --image ${{ secrets.DOCKER_USERNAME }}/dongdaemunfriends-board:latest --force dongdaemunkiller_board