name: Spring Cloud API Gateway CI/CD Pipe line

on:
  push:
    branches:
      - master
    paths:
      - "api-gateway/**"

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Gradle
        working-directory: ./api-gateway
        run: ./gradlew clean build -x test

      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker image Build and Push
        run: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/dongdaemunfriends
          VERSION=${{ github.sha }}
          docker build -t $IMAGE:$VERSION -t $IMAGE:latest .
          docker push $IMAGE:$VERSION
          docker push $IMAGE:latest

      - name: Deploy to Docker Swarm
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/dongdaemunfriends/api-gateway.latest
            docker service update --with-registry-auth --image ${{ secrets.DOCKER_USERNAME }}/dongdaemunfriends/api-gateway:latest --force api-gateway
