name: Docker Stack Deploy CI/CD Piple Line

on:
  push:
    branches:
      - master
    paths:
      - "docker-stack.yml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GIT_ACCESS_KEY: ${{ secrets.GIT_ACCESS_KEY }}
      ENCRYPT_KEY: ${{ secrets.ENCRYPT_KEY }}
      SPRING_PROFILES_ACTIVE: prod

    steps:
      - name: Copy StackFile to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: docker-stack.yml
          target: /home/${{ secrets.SERVER_USER }}/docker-stack.yml
    
      - name: Deploy Docker-Stack
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker stack deploy -c /home/${{ secrets.SERVER_USER }}/docker-stack.yml dongdaemunkiller
